spring.application.name: wesloan
server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password@123
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect